

####################################
server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dattabinit/udemy-rsmortgage-config-repository
          searchPaths: udemy-rsmortgage-customer-service,udemy-rsmortgage-customer-account-service
          username: dattabinit
          password: password123
